version: '3.8'
services:
  db:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ../src/database/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  flask-app:
    container_name: flask-app
    environment:
      - FLASK_APP=src.app
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@db:5432
    build:
      context: ..
      dockerfile: ./dockered/Dockerfile
    ports:
      - '5000:5000'
    restart:
      always
    depends_on:
      - db
volumes:
  db:
    driver: local
